# -*- coding: utf-8 -*-
"""BlockChain Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OkD1tc585JiqHjN51d-Lnr2ypOhI594t
"""

import streamlit as st
import pandas as pd
import hashlib

def create_recharge_ledger():
    """Creates a sample mobile recharge ledger using a Pandas DataFrame."""
    data = {
        'Date': ['2024-03-01', '2024-03-05', '2024-03-10', '2024-03-15', '2024-03-20'],
        'Mobile Number': ['+15551234567', '+15559876543', '+15551234567', '+15551112222', '+15559876543'],
        'Recharge Amount': [20, 50, 10, 30, 25],
        'Operator': ['Verizon', 'AT&T', 'Verizon', 'T-Mobile', 'AT&T'],
        'Recharge Method': ['Credit Card', 'Debit Card', 'PayPal', 'UPI', 'Net Banking']
    }

    ledger = pd.DataFrame(data)
    return ledger

def display_ledger(ledger):
    """Displays the mobile recharge ledger."""

    st.dataframe(ledger)

def generate_hash_key(data):
    """Generates a hash key for the given data."""
    hasher = hashlib.sha256()
    hasher.update(data.to_string().encode())  # Hash the DataFrame as a string
    return hasher.hexdigest()

def main():
    """Main function to demonstrate the mobile recharge ledger."""

    st.title("Mobile Recharge Records Ledger")

    ledger = create_recharge_ledger()
    hash_key = generate_hash_key(ledger)

    # Store the hash key in session state to track changes
    if 'ledger_hash_key' not in st.session_state:
        st.session_state['ledger_hash_key'] = hash_key #Fixed: Added the missing part of the code `state['ledger_hash_key'] = hash_key` and corrected indentation.

    display_ledger(ledger)

#Corrected indentation for `if __name__ == "__main__":` block
if __name__ == "__main__":
    main()